/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProyectoRouteImport } from './routes/proyecto'
import { Route as ContactoRouteImport } from './routes/contacto'
import { Route as ComunidadesRouteImport } from './routes/comunidades'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard.index'
import { Route as DashboardAlertasRouteImport } from './routes/dashboard.alertas'
import { Route as DashboardComunidadIdRouteImport } from './routes/dashboard.comunidad.$id'

const ProyectoRoute = ProyectoRouteImport.update({
  id: '/proyecto',
  path: '/proyecto',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactoRoute = ContactoRouteImport.update({
  id: '/contacto',
  path: '/contacto',
  getParentRoute: () => rootRouteImport,
} as any)
const ComunidadesRoute = ComunidadesRouteImport.update({
  id: '/comunidades',
  path: '/comunidades',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/dashboard/',
  path: '/dashboard/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardAlertasRoute = DashboardAlertasRouteImport.update({
  id: '/dashboard/alertas',
  path: '/dashboard/alertas',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardComunidadIdRoute = DashboardComunidadIdRouteImport.update({
  id: '/dashboard/comunidad/$id',
  path: '/dashboard/comunidad/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/comunidades': typeof ComunidadesRoute
  '/contacto': typeof ContactoRoute
  '/proyecto': typeof ProyectoRoute
  '/dashboard/alertas': typeof DashboardAlertasRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/comunidad/$id': typeof DashboardComunidadIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/comunidades': typeof ComunidadesRoute
  '/contacto': typeof ContactoRoute
  '/proyecto': typeof ProyectoRoute
  '/dashboard/alertas': typeof DashboardAlertasRoute
  '/dashboard': typeof DashboardIndexRoute
  '/dashboard/comunidad/$id': typeof DashboardComunidadIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/comunidades': typeof ComunidadesRoute
  '/contacto': typeof ContactoRoute
  '/proyecto': typeof ProyectoRoute
  '/dashboard/alertas': typeof DashboardAlertasRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/comunidad/$id': typeof DashboardComunidadIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/comunidades'
    | '/contacto'
    | '/proyecto'
    | '/dashboard/alertas'
    | '/dashboard/'
    | '/dashboard/comunidad/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/comunidades'
    | '/contacto'
    | '/proyecto'
    | '/dashboard/alertas'
    | '/dashboard'
    | '/dashboard/comunidad/$id'
  id:
    | '__root__'
    | '/'
    | '/comunidades'
    | '/contacto'
    | '/proyecto'
    | '/dashboard/alertas'
    | '/dashboard/'
    | '/dashboard/comunidad/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ComunidadesRoute: typeof ComunidadesRoute
  ContactoRoute: typeof ContactoRoute
  ProyectoRoute: typeof ProyectoRoute
  DashboardAlertasRoute: typeof DashboardAlertasRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
  DashboardComunidadIdRoute: typeof DashboardComunidadIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/proyecto': {
      id: '/proyecto'
      path: '/proyecto'
      fullPath: '/proyecto'
      preLoaderRoute: typeof ProyectoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contacto': {
      id: '/contacto'
      path: '/contacto'
      fullPath: '/contacto'
      preLoaderRoute: typeof ContactoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/comunidades': {
      id: '/comunidades'
      path: '/comunidades'
      fullPath: '/comunidades'
      preLoaderRoute: typeof ComunidadesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/alertas': {
      id: '/dashboard/alertas'
      path: '/dashboard/alertas'
      fullPath: '/dashboard/alertas'
      preLoaderRoute: typeof DashboardAlertasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/comunidad/$id': {
      id: '/dashboard/comunidad/$id'
      path: '/dashboard/comunidad/$id'
      fullPath: '/dashboard/comunidad/$id'
      preLoaderRoute: typeof DashboardComunidadIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ComunidadesRoute: ComunidadesRoute,
  ContactoRoute: ContactoRoute,
  ProyectoRoute: ProyectoRoute,
  DashboardAlertasRoute: DashboardAlertasRoute,
  DashboardIndexRoute: DashboardIndexRoute,
  DashboardComunidadIdRoute: DashboardComunidadIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
